stages:
  - build
  - deploy

esp8266_v3.3_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp8266-ci-env-new
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v3.3 ${GITLAB_SSH_SERVER}/sdk/ESP8266_RTOS_SDK.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    # - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd esp-idf
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py build

esp8266_master_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp8266-ci-env-new
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone ${GITLAB_SSH_SERVER}/sdk/ESP8266_RTOS_SDK.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd esp-idf
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py build

esp32_master_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py build

esp32_v4.2_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.2 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py build

esp32_v4.0_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.0 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py build

esp32s2_master_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py set-target esp32s2 build

esp32s2_v4.2_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.2 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py set-target esp32s2 build

esp32s3_master_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py set-target esp32s3 build

esp32c3_master_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp-env:v4.4-1
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py set-target esp32c3 build

esp32c3_v4.3_build:
  stage: build
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  tags:
    - build

  variables:
    GIT_STRATEGY: clone
    
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY >> ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

  script:
    - git clone -b release/v4.3 ${GITLAB_SSH_SERVER}/espressif/esp-idf.git esp-idf
    - export IDF_PATH=$(pwd)/esp-idf
    - source $IDF_PATH/tools/ci/configure_ci_environment.sh
    - $IDF_PATH/tools/idf_tools.py --non-interactive install && eval "$($IDF_PATH/tools/idf_tools.py --non-interactive export)" || exit 1
    - cd $IDF_PATH
    - git submodule update --init --recursive
    - cd ..

    - cd examples/light_demo
    - $IDF_PATH/tools/idf.py set-target esp32c3 build

push_master_to_github:
  stage: deploy
  only:
    - master
    - /^release\/v.*$/
  tags:
    - deploy
  when: on_success
  image: $CI_DOCKER_REGISTRY/esp32-ci-env
  variables:
    GIT_STRATEGY: clone
    GITHUB_PUSH_REFS: refs/remotes/origin/release refs/remotes/origin/master
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GH_PUSH_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git remote add github git@github.com:espressif/esp-joylink.git
    # - git push --follow-tags github HEAD:master
    - eval $(git for-each-ref --shell bash --format 'if [ $CI_COMMIT_SHA == %(objectname) ]; then git checkout -B %(refname:strip=3); git push --follow-tags github %(refname:strip=3); fi;' $GITHUB_PUSH_REFS)
