ARCH=x86
CHIP=
#ARCH=mtk
#CHIP=7687

#=======  EDITER =============
PROJECT_ROOT_PATH:=/home/lizw/workspace/joylink2.0/joylink_dev_release2/joylink_dev_sdk_2.0.09

#======= TARGET =======
TARGET_BIN=${PROJECT_ROOT_PATH}/target/bin

#======= PLAT FROM =============
ifeq (${CHIP}, )  
PLATFORM=${ARCH}
else
PLATFORM=${ARCH}_${CHIP}
endif

include ${PROJECT_ROOT_PATH}/scripts/${PLATFORM}.mk
INCLUDES+= -I${PROJECT_ROOT_PATH}
INCLUDES+= -I${PROJECT_ROOT_PATH}/example/
INCLUDES+= -I${PROJECT_ROOT_PATH}/config/

TARGET_LIB=${PROJECT_ROOT_PATH}/target/lib

#====== COMMON ======

RM = rm -rf
CP = cp -rf
MV = mv -f

LIBS += -lm 

#AGENT_GW_EN=yes
ifeq (${AGENT_GW_EN}, yes)  
CFLAGS += -D_AGENT_GW_
endif

#CFLAGS += -D_SAVE_FILE_

DEBUG=y
ifeq ($(DEBUG), y)
CFLAGS += -D_GET_HOST_BY_NAME_
else
CFLAGS += -O2
endif

#=======================
